export { getProducts, searchProducts, getProductById, createProduct, updateProduct, deleteProduct, getSearchSuggestions, getTrendingSearches, getCategories } from './productService'
export { syncCartToBackend, fetchCartFromBackend, updateCartItemBackend, removeCartItemBackend, applyDiscountBackend, removeDiscountBackend, getCartSummaryBackend } from './cartService'
export { placeOrder, getOrderById, getOrders, cancelOrder, reorder } from './orderService'
export { getWishlist, addToWishlist, removeFromWishlist } from './wishlistService'
export { getProductReviews, createReview, updateReview, deleteReview } from './reviewService'
export { getAdminOrders, getAdminOrderById, updateOrderStatus, updateOrderTracking, getAdminDashboardStats, getAdminUsers, getAdminUserById, getAdminAuditLogs } from './adminService'
export { apiClient, setAuthToken, clearAuthToken } from './apiClient'
export * as authService from './authService'
export * as profileService from './profileService'
